spring.datasource.url=jdbc:mysql://reseau.proxy.rlwy.net:24065/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=YUjLZnZoWQtLYUOhYBVyGXMZKMmscmTj
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=mysupersecretkeymysupersecretkey12345
jwt.expiration=864000

server.port=${PORT:8080}